### ISSUE TITLE
As a admin I want to generate report either per project or user

### ISSUE THREAD

**Issue by radekkaminski** [nexocodecom/nisse.io#29]
1. add interactive message with date range pre-sets before launching report form (with additional options "This 2 weeks" and "Previous 2 weeks"
2. if admin has chosen project then generate spreadsheet with entries grouped by user
3. if admin has chosen user then generate spreadsheet with entries grouped by project
4. split hours in the report into 2 columns: basic hours, overtime with totals at the end
5. split hours same way as above in the "/ni list" result

remove unnecessary columns (project, employee) depending on context

**Comment by wgebis** [comment]
Done in v0.4
