### ISSUE TITLE
Inside app channel /ni command prefix shouldn't be necessary 

### ISSUE THREAD

**Issue by witali-nc** [nexocodecom/nisse.io#40]
Inside application channel, should be possible to write commands without /ni prefix

**Comment by wgebis** [comment]
@witali-nc I'm affraid that Slack requires prompting `/commnad` every channel/chat etc. Please let me know in case there is such possibility.

**Comment by wgebis** [comment]
It is possible to implement the simpler version of interaction via Slack<->API (without Slack command prefix) e.g. via RTM API with the pure Slack mesages. 
https://api.slack.com/events/message
