### ISSUE TITLE
Reporting days off

### ISSUE THREAD

**Issue by radekkaminski** [nexocodecom/nisse.io#46]
1. let the user report days off (future dates only)
2. let user delete reported days off (available until date of start)
3. push days off from nisse to google calendar (Urlopy) according to days off - nisse should publish this data by accessing google calendar api (configurable way)

**Comment by andrzejderylo** [comment]
I would amend  **1.** to let the user report days off for current day and future dates - sometimes people would like to take a emergency day off right at the free day. What do you think?

**Comment by wgebis** [comment]
Done in #48
