### ISSUE TITLE
Prevent generate future reports

### ISSUE THREAD

**Issue by wojtek1150** [nexocodecom/nisse.io#66]
**Problem:**
When you generate a report for the current month (first-last day) days that are not added yet are still included to `Total hours` for example 8 days with 11.25 overtime

1. For whole month
![image](https://user-images.githubusercontent.com/5401942/53032882-0ff1d800-3470-11e9-8841-7b992ad21ef1.png)

2. First day to now
![image](https://user-images.githubusercontent.com/5401942/53032955-3a439580-3470-11e9-9e3b-e0976e9be892.png)

**Solution**
Prevent somehow to select the date from the future

**Comment by wgebis** [comment]
Solved in v0.7
